# Generated by Django 5.0.3 on 2024-09-04 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('peran', models.CharField(choices=[('siswa', 'Siswa'), ('guru', 'Guru'), ('wali_siswa', 'Wali Siswa')], max_length=20)),
                ('kelas', models.CharField(blank=True, max_length=20)),
                ('anonim', models.BooleanField(default=False)),
                ('jenis_pengaduan', models.CharField(choices=[('bullying_perundungan', 'Bullying / Perundungan'), ('saran_kritik', 'Saran atau Kritik untuk Sekolah'), ('keluhan_lainnya', 'Keluhan Lainnya')], max_length=50)),
                ('deskripsi', models.TextField()),
                ('bukti', models.FileField(blank=True, upload_to='uploads/bukti/')),
                ('tanggal_pengaduan', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
