# Generated by Django 5.0.3 on 2024-09-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaduan',
            name='bukti',
            field=models.FileField(blank=True, upload_to='bukti/'),
        ),
    ]
