# Generated by Django 5.0.3 on 2024-09-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0002_alter_pengaduan_bukti'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='nomor_whatsapp',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
